# Generated by Django 3.2.25 on 2025-05-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('sponsor_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Legislator',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('bill_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VoteResult',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('legislator_id', models.BigIntegerField()),
                ('vote_id', models.BigIntegerField()),
                ('vote_type', models.IntegerField()),
            ],
        ),
    ]
