# Generated by Django 3.2.25 on 2025-05-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='sponsor_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
