# Generated by Django 3.2.25 on 2025-05-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_bill_sponsor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="sponsor_id",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="voteresult",
            name="vote_type",
            field=models.IntegerField(choices=[(1, "Supported"), (2, "Opposed")]),
        ),
    ]
